### ISSUE TITLE
NEXT button on availability page in Volunteer Flow

### ISSUE THREAD

**Issue by saquibaijaz** [navgurukul/bhanwari-devi#682]
**Describe the bug**
The NEXT button on the availability page in the Volunteer flow is not working as expected.

**To Reproduce**
1. Login to Volunteer flow
2. Go to the availability page
3. Fill in the availability
4. The NEXT button gets enabled
5. Remove the availability
6. The NEXT button is still enabled
7. Click the NEXT button and move to the next step

**Expected behaviour**
The NEXT button should be disabled when the availability is removed, and the user should not be able to move to the next step without filling in their availability.

**Screenshots**
https://drive.google.com/file/d/1sGdzfs5l0--UxR2UyqrHtLQI4McSUtOU/view?usp=sharing

**Refer Sheet**
Weekly Testing Bugs, Test Case 4

**Comment by kartiks26** [comment]
@saquibaijaz Please check this fixed in dev

**Comment by saquibaijaz** [comment]
@

https://user-images.githubusercontent.com/111858763/192957024-7d839d75-258e-4487-98ec-ad9ddd102c08.mp4

@kartiks26 Please check this out. you can connect with me if you need more explanation.

**Comment by kartiks26** [comment]
@saquibaijaz I miss interpreted it !! sorry  Will fix it rn

**Comment by kartiks26** [comment]
@saquibaijaz Please retry in 10 mins

**Comment by saquibaijaz** [comment]
@kartiks26 , brother it's still the same. is it on dev or are you testing it in your local environment?

**Comment by kartiks26** [comment]
@saquibaijaz The build Seems to failed due to some reason

**Comment by kartiks26** [comment]
![image](https://user-images.githubusercontent.com/84696578/193089119-44994a7a-f2e7-40a0-91f3-66b5459d5570.png)
See in this the latest commit dont have the deployed comment

**Comment by saquibaijaz** [comment]
@kartiks26 All right. Let me know once done

**Comment by kartiks26** [comment]
Sure

**Comment by saquibaijaz** [comment]
@kartiks26 , not working. If we remove the time then also the button is enabled.

**Comment by Poonam-Singh-Bagh** [comment]
@saquibaijaz can you try it once again https://bhanwari-devi.vercel.app/volunteer-form
If still it's not fixed for you we'll do a call because we 3 @komalahire @kartiks26 and I tested it, it's working fine.

**Comment by saquibaijaz** [comment]
@Poonam-Singh-Bagh @kartiks26 
working fine now.
